// Assembly TumblOne, Version 1.0.4.0

[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCopyright("Originally 2013 by Helena.")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTitle("TumblTwo")]
[assembly: System.Reflection.AssemblyDescription("This tool intended for crawling images of Tumblr blogs. Use on own risk. This product is OpenSource.")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("jzab.de")]
[assembly: System.Reflection.AssemblyProduct("TumblTwo")]
//[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(true)]
[assembly: System.Runtime.InteropServices.Guid("6a73a9ba-9dae-4be9-a7e5-fdd73413dd9f")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.6.0")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]