namespace TumblOne
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Drawing;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Runtime.InteropServices;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.Threading;
    using System.Windows.Forms;
    using System.Xml.Linq;

    public partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        /// 
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(Form1));
            this.label21 = new Label();
            this.tBlogUrl = new TextBox();
            this.label1 = new Label();
            this.chkGIF = new CheckBox();
            this.lblUrl = new Label();
            this.lblProcess = new Label();
            this.lbl23 = new Label();
            this.contextBlog = new ContextMenuStrip(this.components);
            this.mnuShowFilesInExplorer = new ToolStripMenuItem();
            this.mnuRemoveBlog2 = new ToolStripMenuItem();
            this.toolStripMenuItem2 = new ToolStripSeparator();
            this.mnuCrawl = new ToolStripMenuItem();
            this.mnuVisit = new ToolStripMenuItem();
            this.toolStrip1 = new ToolStrip();
            this.toolAddBlog = new ToolStripButton();
            this.toolRemoveBlog = new ToolStripButton();
            this.toolShowExplorer = new ToolStripButton();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.toolCrawl = new ToolStripButton();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.toolPause = new ToolStripButton();
            this.toolResume = new ToolStripButton();
            this.toolStop = new ToolStripButton();
            this.toolStripSeparator3 = new ToolStripSeparator();
            this.toolAbout = new ToolStripButton();
            this.columnHeader5 = new ColumnHeader();
            this.columnHeader8 = new ColumnHeader();
            this.columnHeader6 = new ColumnHeader();
            this.pgBar = new ProgressBar();
            this.groupBox1 = new GroupBox();
            this.panelInfo = new Panel();
            this.label2 = new Label();
            this.smallImage = new PictureBox();
            this.lvBlog = new ListViewEx();
            this.columnHeader1 = new ColumnHeader();
            this.columnHeader3 = new ColumnHeader();
            this.columnHeader4 = new ColumnHeader();
            this.contextBlog.SuspendLayout();
            this.toolStrip1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.panelInfo.SuspendLayout();
            ((ISupportInitialize)this.smallImage).BeginInit();
            base.SuspendLayout();
            this.label21.AutoSize = true;
            this.label21.Location = new Point(6, 0x49);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x3f, 13);
            this.label21.TabIndex = 2;
            this.label21.Text = "Current Url: ";
            this.tBlogUrl.BackColor = Color.LightSteelBlue;
            this.tBlogUrl.BorderStyle = BorderStyle.FixedSingle;
            this.tBlogUrl.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.tBlogUrl.ForeColor = Color.Black;
            this.tBlogUrl.Location = new Point(0x87, 0x10);
            this.tBlogUrl.Name = "tBlogUrl";
            this.tBlogUrl.Size = new Size(0x1b1, 0x15);
            this.tBlogUrl.TabIndex = 1;
            this.tBlogUrl.Text = "http://";
            this.label1.AutoSize = true;
            this.label1.ForeColor = Color.White;
            this.label1.Location = new Point(9, 0x13);
            this.label1.Name = "label1";
            this.label1.Size = new Size(120, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "Enter a valid Tumblr Url:";
            this.chkGIF.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.chkGIF.AutoSize = true;
            this.chkGIF.Checked = true;
            this.chkGIF.CheckState = CheckState.Checked;
            this.chkGIF.Location = new Point(0x128, 0x13);
            this.chkGIF.Name = "chkGIF";
            this.chkGIF.Size = new Size(0x5b, 0x11);
            this.chkGIF.TabIndex = 8;
            this.chkGIF.Text = "Skip GIF-Files";
            this.chkGIF.UseVisualStyleBackColor = true;
            this.lblUrl.ForeColor = Color.Yellow;
            this.lblUrl.Location = new Point(6, 0x5d);
            this.lblUrl.Name = "lblUrl";
            this.lblUrl.Size = new Size(0x173, 0x31);
            this.lblUrl.TabIndex = 7;
            this.lblUrl.Text = "       ";
            this.lblUrl.TextAlign = ContentAlignment.MiddleLeft;
            this.lblProcess.AutoSize = true;
            this.lblProcess.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.lblProcess.ForeColor = Color.Yellow;
            this.lblProcess.Location = new Point(6, 0x31);
            this.lblProcess.Name = "lblProcess";
            this.lblProcess.Size = new Size(0x4f, 13);
            this.lblProcess.TabIndex = 6;
            this.lblProcess.Text = "                  ";
            this.lbl23.AutoSize = true;
            this.lbl23.Location = new Point(6, 0x1b);
            this.lbl23.Name = "lbl23";
            this.lbl23.Size = new Size(0x55, 13);
            this.lbl23.TabIndex = 5;
            this.lbl23.Text = "Current Process:";
            this.contextBlog.Items.AddRange(new ToolStripItem[] { this.mnuShowFilesInExplorer, this.mnuRemoveBlog2, this.toolStripMenuItem2, this.mnuCrawl, this.mnuVisit });
            this.contextBlog.Name = "contextBlog";
            this.contextBlog.Size = new Size(0x109, 0xa2);
            this.mnuShowFilesInExplorer.Image = TumblOne.Properties.Resources.Explorer;
            this.mnuShowFilesInExplorer.ImageScaling = ToolStripItemImageScaling.None;
            this.mnuShowFilesInExplorer.Name = "mnuShowFilesInExplorer";
            this.mnuShowFilesInExplorer.Size = new Size(0x108, 0x26);
            this.mnuShowFilesInExplorer.Text = "Show Files in Windows Explorer...";
            this.mnuShowFilesInExplorer.Click += new EventHandler(this.mnuShowFilesInExplorer_Click);
            this.mnuRemoveBlog2.Image = TumblOne.Properties.Resources.Remove;
            this.mnuRemoveBlog2.ImageScaling = ToolStripItemImageScaling.None;
            this.mnuRemoveBlog2.Name = "mnuRemoveBlog2";
            this.mnuRemoveBlog2.Size = new Size(0x108, 0x26);
            this.mnuRemoveBlog2.Text = "Remove Blog";
            this.mnuRemoveBlog2.Click += new EventHandler(this.RemoveBlog);
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new Size(0x105, 6);
            this.mnuCrawl.Image = TumblOne.Properties.Resources.Scan;
            this.mnuCrawl.ImageScaling = ToolStripItemImageScaling.None;
            this.mnuCrawl.Name = "mnuCrawl";
            this.mnuCrawl.Size = new Size(0x108, 0x26);
            this.mnuCrawl.Text = "Crawl selected Blog";
            this.mnuCrawl.Click += new EventHandler(this.mnuRescanBlog_Click);
            this.mnuVisit.Name = "mnuVisit";
            this.mnuVisit.Size = new Size(0x108, 0x26);
            this.mnuVisit.Text = "Visit in Internet Browser...";
            this.mnuVisit.Click += new EventHandler(this.mnuVisit_Click);
            this.toolStrip1.BackColor = Color.SlateGray;
            this.toolStrip1.Dock = DockStyle.Right;
            this.toolStrip1.GripStyle = ToolStripGripStyle.Hidden;
            this.toolStrip1.ImageScalingSize = new Size(0x20, 0x20);
            this.toolStrip1.Items.AddRange(new ToolStripItem[] { this.toolAddBlog, this.toolRemoveBlog, this.toolShowExplorer, this.toolStripSeparator1, this.toolCrawl, this.toolStripSeparator2, this.toolPause, this.toolResume, this.toolStop, this.toolStripSeparator3, this.toolAbout });
            this.toolStrip1.Location = new Point(0x251, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.RenderMode = ToolStripRenderMode.System;
            this.toolStrip1.Size = new Size(0x52, 0x1d3);
            this.toolStrip1.TabIndex = 6;
            this.toolStrip1.Text = "toolStrip1";
            this.toolAddBlog.Image = TumblOne.Properties.Resources.AddBlog;
            this.toolAddBlog.ImageTransparentColor = Color.Magenta;
            this.toolAddBlog.Name = "toolAddBlog";
            this.toolAddBlog.Size = new Size(0x4f, 0x33);
            this.toolAddBlog.Text = "Add Blog";
            this.toolAddBlog.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolAddBlog.ToolTipText = "Add a nw Blog to Library...";
            this.toolAddBlog.Click += new EventHandler(this.AddBlog);
            this.toolRemoveBlog.Image = TumblOne.Properties.Resources.Remove;
            this.toolRemoveBlog.ImageTransparentColor = Color.Magenta;
            this.toolRemoveBlog.Name = "toolRemoveBlog";
            this.toolRemoveBlog.Size = new Size(0x4f, 0x33);
            this.toolRemoveBlog.Text = "Remove Blog";
            this.toolRemoveBlog.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolRemoveBlog.ToolTipText = "Remove current Blog and all dowloaded Images...";
            this.toolRemoveBlog.Click += new EventHandler(this.RemoveBlog);
            this.toolShowExplorer.Enabled = false;
            this.toolShowExplorer.Image = TumblOne.Properties.Resources.Explorer;
            this.toolShowExplorer.ImageTransparentColor = Color.Magenta;
            this.toolShowExplorer.Name = "toolShowExplorer";
            this.toolShowExplorer.Size = new Size(0x4f, 0x33);
            this.toolShowExplorer.Text = "Show Files";
            this.toolShowExplorer.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolShowExplorer.ToolTipText = "Show Files of selected Blog in Windows Explorer...";
            this.toolShowExplorer.Click += new EventHandler(this.mnuShowFilesInExplorer_Click);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new Size(0x4f, 6);
            this.toolCrawl.Image = TumblOne.Properties.Resources.Scan;
            this.toolCrawl.ImageTransparentColor = Color.Magenta;
            this.toolCrawl.Name = "toolCrawl";
            this.toolCrawl.Size = new Size(0x4f, 0x33);
            this.toolCrawl.Text = "Crawl";
            this.toolCrawl.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolCrawl.ToolTipText = "Crawl current Blog for Images...";
            this.toolCrawl.Click += new EventHandler(this.mnuRescanBlog_Click);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new Size(0x4f, 6);
            this.toolPause.Enabled = false;
            this.toolPause.Image = TumblOne.Properties.Resources.Pause;
            this.toolPause.ImageTransparentColor = Color.Magenta;
            this.toolPause.Name = "toolPause";
            this.toolPause.Size = new Size(0x4f, 0x33);
            this.toolPause.Text = "Pause";
            this.toolPause.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolPause.ToolTipText = "Pause current Process...";
            this.toolPause.Click += new EventHandler(this.toolPause_Click);
            this.toolResume.Enabled = false;
            this.toolResume.Image = TumblOne.Properties.Resources.Resume;
            this.toolResume.ImageTransparentColor = Color.Magenta;
            this.toolResume.Name = "toolResume";
            this.toolResume.Size = new Size(0x4f, 0x33);
            this.toolResume.Text = "Resume";
            this.toolResume.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolResume.ToolTipText = "Continue last Process...";
            this.toolResume.Click += new EventHandler(this.toolResume_Click);
            this.toolStop.Enabled = false;
            this.toolStop.Image = TumblOne.Properties.Resources.Stop;
            this.toolStop.ImageTransparentColor = Color.Magenta;
            this.toolStop.Name = "toolStop";
            this.toolStop.Size = new Size(0x4f, 0x33);
            this.toolStop.Text = "Stop";
            this.toolStop.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolStop.ToolTipText = "Stop current Process...";
            this.toolStop.Click += new EventHandler(this.toolStop_Click);
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new Size(0x4f, 6);
            this.toolAbout.Image = TumblOne.Properties.Resources.About;
            this.toolAbout.ImageTransparentColor = Color.Magenta;
            this.toolAbout.Name = "toolAbout";
            this.toolAbout.Size = new Size(0x4f, 0x33);
            this.toolAbout.Text = "About";
            this.toolAbout.TextImageRelation = TextImageRelation.ImageAboveText;
            this.toolAbout.Click += new EventHandler(this.toolAbout_Click);
            this.columnHeader5.Text = "Filename";
            this.columnHeader5.Width = 0x9a;
            this.columnHeader8.Text = "Downloaded";
            this.columnHeader8.Width = 0x52;
            this.columnHeader6.Text = "Url";
            this.columnHeader6.Width = 0x17e;
            this.pgBar.Location = new Point(6, 0x9b);
            this.pgBar.Name = "pgBar";
            this.pgBar.Size = new Size(0x17d, 0x17);
            this.pgBar.TabIndex = 9;
            this.groupBox1.Controls.Add(this.lblUrl);
            this.groupBox1.Controls.Add(this.label21);
            this.groupBox1.Controls.Add(this.chkGIF);
            this.groupBox1.Controls.Add(this.pgBar);
            this.groupBox1.Controls.Add(this.lbl23);
            this.groupBox1.Controls.Add(this.lblProcess);
            this.groupBox1.ForeColor = Color.White;
            this.groupBox1.Location = new Point(12, 0x10f);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x189, 0xb8);
            this.groupBox1.TabIndex = 10;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Download";
            this.panelInfo.Controls.Add(this.label2);
            this.panelInfo.Location = new Point(11, 0x10f);
            this.panelInfo.Name = "panelInfo";
            this.panelInfo.Size = new Size(0x22d, 0xb8);
            this.panelInfo.TabIndex = 11;
            this.label2.Dock = DockStyle.Fill;
            this.label2.Font = new Font("Forte", 15.75f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label2.ForeColor = Color.IndianRed;
            this.label2.Location = new Point(0, 0);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x22d, 0xb8);
            this.label2.TabIndex = 0;
            this.label2.Text = "Click on a Blog and hit Crawl Button, to start the Crawl Process. ";
            this.label2.TextAlign = ContentAlignment.MiddleCenter;
            this.smallImage.Anchor = AnchorStyles.Right | AnchorStyles.Top;
            this.smallImage.BackColor = Color.LightSteelBlue;
            this.smallImage.BorderStyle = BorderStyle.FixedSingle;
            this.smallImage.Location = new Point(0x19b, 0x10f);
            this.smallImage.Name = "smallImage";
            this.smallImage.Size = new Size(0x9d, 0xb8);
            this.smallImage.SizeMode = PictureBoxSizeMode.StretchImage;
            this.smallImage.TabIndex = 7;
            this.smallImage.TabStop = false;
            this.lvBlog.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.lvBlog.BackColor = Color.LightSteelBlue;
            this.lvBlog.BorderStyle = BorderStyle.FixedSingle;
            this.lvBlog.Columns.AddRange(new ColumnHeader[] { this.columnHeader1, this.columnHeader3, this.columnHeader4 });
            this.lvBlog.ContextMenuStrip = this.contextBlog;
            this.lvBlog.ForeColor = Color.Black;
            this.lvBlog.FullRowSelect = true;
            this.lvBlog.HeaderStyle = ColumnHeaderStyle.Nonclickable;
            this.lvBlog.HideSelection = false;
            this.lvBlog.Location = new Point(12, 0x2a);
            this.lvBlog.MultiSelect = false;
            this.lvBlog.Name = "lvBlog";
            this.lvBlog.Size = new Size(0x22d, 0xdf);
            this.lvBlog.Sorting = SortOrder.Ascending;
            this.lvBlog.TabIndex = 0;
            this.lvBlog.UseCompatibleStateImageBehavior = false;
            this.lvBlog.View = View.Details;
            this.columnHeader1.Text = "Name";
            this.columnHeader1.Width = 0x85;
            this.columnHeader3.Text = "Downloaded Images";
            this.columnHeader3.TextAlign = HorizontalAlignment.Center;
            this.columnHeader3.Width = 0x77;
            this.columnHeader4.Text = "Url";
            this.columnHeader4.Width = 0x121;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
//            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.LightSlateGray;
            base.ClientSize = new Size(0x2a3, 0x1d3);
            base.Controls.Add(this.panelInfo);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.smallImage);
            base.Controls.Add(this.toolStrip1);
            base.Controls.Add(this.lvBlog);
            base.Controls.Add(this.tBlogUrl);
            base.Controls.Add(this.label1);
//            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.Icon = (Icon)resources.GetObject("TumblOne");
            base.MaximizeBox = false;
            base.Name = "Form1";
//            base.SizeGripStyle = SizeGripStyle.Hide;
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "TumblOne - A Tumblr Image Crawler Version 1.0.4";
            base.FormClosing += new FormClosingEventHandler(this.Form1_FormClosing);
            base.Load += new EventHandler(this.Form1_Load);
            this.contextBlog.ResumeLayout(false);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.panelInfo.ResumeLayout(false);
            ((ISupportInitialize)this.smallImage).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        #endregion

        private CheckBox chkGIF;
        private ColumnHeader columnHeader1;
        private ColumnHeader columnHeader3;
        private ColumnHeader columnHeader4;
        private ColumnHeader columnHeader5;
        private ColumnHeader columnHeader6;
        private ColumnHeader columnHeader8;
        //private IContainer components;
        private ContextMenuStrip contextBlog;
        private GroupBox groupBox1;
        private Label label1;
        private Label label2;
        public Label label21;
        public Label lbl23;
        public Label lblProcess;
        public Label lblUrl;
        public ListViewEx lvBlog;
        private ToolStripMenuItem mnuCrawl;
        private ToolStripMenuItem mnuRemoveBlog2;
        private ToolStripMenuItem mnuShowFilesInExplorer;
        private ToolStripMenuItem mnuVisit;
        private Panel panelInfo;
        private ProgressBar pgBar;
        private PictureBox smallImage;
        private TextBox tBlogUrl;
        private ToolStripButton toolAbout;
        private ToolStripButton toolAddBlog;
        private ToolStripButton toolCrawl;
        private ToolStripButton toolPause;
        private ToolStripButton toolRemoveBlog;
        private ToolStripButton toolResume;
        private ToolStripButton toolShowExplorer;
        private ToolStripButton toolStop;
        private ToolStrip toolStrip1;
        private ToolStripSeparator toolStripMenuItem2;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripSeparator toolStripSeparator3;
        private ManualResetEvent wait_handle;
    }
}
